### PR TITLE
feat: Adds support for routing tables

### PR DESCRIPTION
**Pull request by AMacedoP**
Adds a new field in CRD to configure the routing table the route will be installed in. If not set it will use the `TARGET_TABLE` env.

### CODE REVIEW

**Comment by AMacedoP** [comment]
Hi @mihivagyok, can you add the rewievers for this PR?

**Review by Tamas-Biro1 — CHANGES_REQUESTED** [review]
hi @AMacedoP thanks for your contribution!

I reviewed and tried out your PR, it looks awesome. 
Just one small change request: we have a functional verification test (FVT) suite which verifies the basic functionality of the static route operator (you can find it under `scripts` folder). Could you add few tests to it to verify this new functionality?

I tested your PR with these changes, but there might be more test cases needed:
```
diff --git a/scripts/fvt-tools.sh b/scripts/fvt-tools.sh
index 3a1cb47..7bc7b97 100755
--- a/scripts/fvt-tools.sh
+++ b/scripts/fvt-tools.sh
@@ -230,6 +230,7 @@ check_operator_is_running() {
 # - CR name
 # - Node name (optional, needed when a CR applies only for a given node)
 # - Test type which is able to differentiate positive or negative tests
+# - Table ID, if not specified fall back to default
 check_route_on_nodes() {
   local route=$1
   local match_node="${2:-all}"
@@ -237,6 +238,7 @@ check_route_on_nodes() {
   local match=false
   local passed=false
   local routes
+  local table="${4:-all}"
   for node in "${NODES[@]}"; do
     # Execute the command on all the nodes or only the given node
     if [[ "${match_node}" == "all" ]] ||
@@ -244,7 +246,7 @@ check_route_on_nodes() {
       match=true
       passed=false
       for _ in $(seq ${SLEEP_COUNT}); do
-        routes=$(exec_in_hostnet_of_node "${node}" 'ip route')
+        routes=$(exec_in_hostnet_of_node "${node}" "ip route show table ${table}")
         if [[ "${test_type}" == "positive" ]] &&
           [[ ${routes} == *${route}* ]]; then
           fvtlog "Passed: The route was found on node ${node}!"
@@ -321,3 +323,4 @@ manage_common_operator_resources() {
 pick_protected_subnet() {
   echo "${1}" | cut -d, -f1
 }
+
diff --git a/scripts/run-fvt.sh b/scripts/run-fvt.sh
index ac4f689..9a69f61 100755
--- a/scripts/run-fvt.sh
+++ b/scripts/run-fvt.sh
@@ -279,4 +279,17 @@ EOF
   kubectl delete staticroute example-static-route-no-match
 fi

+fvtlog "Test adding route to non-default routing table"
+cat <<EOF | kubectl apply -f -
+apiVersion: static-route.ibm.com/v1
+kind: StaticRoute
+metadata:
+  name: example-static-route-to-non-default-routing-table
+spec:
+  subnet: "192.168.0.0/24"
+  table: 200
+EOF
+check_route_on_nodes "192.168.0.0/24 via ${GW}" "all" "positive" "200"
+
 fvtlog "All tests passed!"
+
```

and the results of it:
```
2024-03-14 11:42:52 UTC [fvt] Test adding route to non-default routing table
staticroute.static-route.ibm.com/example-static-route-to-non-default-routing-table created
2024-03-14 11:42:53 UTC [fvt] Passed: The route was found on node static-route-operator-fvt-control-plane!
2024-03-14 11:42:53 UTC [fvt] Passed: The route was found on node static-route-operator-fvt-worker!
2024-03-14 11:42:54 UTC [fvt] Passed: The route was found on node static-route-operator-fvt-worker2!
2024-03-14 11:42:54 UTC [fvt] All tests passed!
```

**Comment by AMacedoP** [comment]
@Tamas-Biro1 sorry for the late reply, I was in vacation. I added the requested test that is similar to the one you showed, I'm not sure if other cases are needed. Tell me what you think

**Comment by AMacedoP** [comment]
Hi @Tamas-Biro1, do you have any comments?

**Review by Tamas-Biro1 — APPROVED** [review]

**Review by tamassoos3 — APPROVED** [review]

**Review by SzabolcsSzoke — APPROVED** [review]

**Pull request merged**
